name: Build on Ubuntu

on:
  push:
    branches:
      - test-br

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: /var/www/html/

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y mariadb-server
        sudo systemctl enable mariadb.service
        sudo systemctl start mariadb.service

    - name: Build Project
      run: |
        sudo ufw enable 
        sudo ufw allow 3306
        sudo service ufw restart
    - name: config database
      run: |
        sudo mariadb -e  'CREATE DATABASE ecomdb;'
        sudo  mariadb   -e "CREATE USER 'ecomuser'@'localhost' IDENTIFIED BY 'ecompassword';"
        sudo mariadb -e "GRANT ALL PRIVILEGES ON *.* TO 'ecomuser'@'localhost';"
        sudo mariadb -e "FLUSH PRIVILEGES;"

    - name: create and run mysqlscript 
      run: |
        sudo  cat > db-load-script.sql <<-EOF
        USE ecomdb;
        CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;
        
        INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");
        
        EOF
        sudo mariadb  < db-load-script.sql   

    - name: Deploy and Configure Web na and upload content
      run: |
        sudo apt-get update
        sudo apt-get install php libapache2-mod-php php-mysql -y
        sudo ufw allow 'Apache Full'
        sudo sed -i 's/index.html/index.php/g' /etc/apache2/apache2.conf
        curl http://localhost
     


