name: Build on Ubuntu

on:
  push:
    branches:
      - test-br

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y mariadb-server
        sudo systemctl enable mariadb.service
        sudo systemctl start mariadb.service

    - name: Build Project
      run: |
        sudo ufw enable 
        sudo ufw allow 3306
        sudo service ufw restart
        



