name: Build on Ubuntu

on:
  push:
    branches:
      - test-br

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y mariadb-server
        sudo systemctl enable mariadb.service
        sudo systemctl start mariadb.service

    - name: Build Project
      run: |
        sudo ufw enable 
        sudo ufw allow 3306
        sudo service ufw restart
    - name: config dattabase
      run: |
        sudo  mariadb
        GRANT ALL ON *.* TO 'admin'@'localhost' IDENTIFIED BY 'dbadminpassW23' WITH GRANT OPTION;   
        



